// leave off @2x/@3x
const images = {
  carIcon0: require('./Hino Connect Car Icon0.svg'),
  activedCarIcon0: require('./Actived/Actived Hino Connect Car Icon0.svg'),
  carIcon1: require('./Hino Connect Car Icon1.svg'),
  activedCarIcon1: require('./Actived/Actived Hino Connect Car Icon1.svg'),
  carIcon2: require('./Hino Connect Car Icon2.svg'),
  activedCarIcon2: require('./Actived/Actived Hino Connect Car Icon2.svg'),
  carIcon3: require('./Hino Connect Car Icon3.svg'),
  activedCarIcon3: require('./Actived/Actived Hino Connect Car Icon3.svg'),
  carIcon4: require('./Hino Connect Car Icon4.svg'),
  activedCarIcon4: require('./Actived/Actived Hino Connect Car Icon4.svg'),
  carIcon5: require('./Hino Connect Car Icon5.svg'),
  activedCarIcon5: require('./Actived/Actived Hino Connect Car Icon5.svg'),
  carIcon6: require('./Hino Connect Car Icon6.svg'),
  activedCarIcon6: require('./Actived/Actived Hino Connect Car Icon6.svg'),
  tireCar: require('./tireCar.svg'),
  tireIcon: require('./tireIcon.svg'),
  Tire_pressure_sensor_not_install4: require('./Tire_pressure_sensor_not_install4.svg'),
  car1: require('./Car/(No BG) Hino Car Icon1.svg'),
  car2: require('./Car/(No BG) Hino Car Icon2.svg'),
  car3: require('./Car/(No BG) Hino Car Icon3.svg'),
  car4: require('./Car/(No BG) Hino Car Icon4.svg'),
  car5: require('./Car/(No BG) Hino Car Icon5.svg'),
  car6: require('./Car/(No BG) Hino Car Icon6.svg'),
  car7: require('./Car/(No BG) Hino Car Icon6.svg'),
  car1_red: require('./Car/(Red) Hino Car Icon1.svg'),
  car2_red: require('./Car/(Red) Hino Car Icon2.svg'),
  car3_red: require('./Car/(Red) Hino Car Icon3.svg'),
  car4_red: require('./Car/(Red) Hino Car Icon4.svg'),
  car5_red: require('./Car/(Red) Hino Car Icon5.svg'),
  car6_red: require('./Car/(Red) Hino Car Icon6.svg'),
  car7_red: require('./Car/(Red) Hino Car Icon7.svg'),
  car1_yellow: require('./Car/(Yellow) Hino Car Icon1.svg'),
  car2_yellow: require('./Car/(Yellow) Hino Car Icon2.svg'),
  car3_yellow: require('./Car/(Yellow) Hino Car Icon3.svg'),
  car4_yellow: require('./Car/(Yellow) Hino Car Icon4.svg'),
  car5_yellow: require('./Car/(Yellow) Hino Car Icon5.svg'),
  car6_yellow: require('./Car/(Yellow) Hino Car Icon6.svg'),
  car7_yellow: require('./Car/(Yellow) Hino Car Icon7.svg'),
  car1_green: require('./Car/(Green) Hino Car Icon1.svg'),
  car2_green: require('./Car/(Green) Hino Car Icon2.svg'),
  car3_green: require('./Car/(Green) Hino Car Icon3.svg'),
  car4_green: require('./Car/(Green) Hino Car Icon4.svg'),
  car5_green: require('./Car/(Green) Hino Car Icon5.svg'),
  car6_green: require('./Car/(Green) Hino Car Icon6.svg'),
  car7_green: require('./Car/(Green) Hino Car Icon7.svg'),
  cluster: require('./Cluster.png'),
  DriverAvatar: require('./DriverAvatar.png'),
  //#region Image By Class Type

  // ACTIVE
  Green_Actived_1: require('./ByClassType/Active/4W/1-Green-Actived.svg'),
  Grey_Actived_1: require('./ByClassType/Active/4W/1-Grey-Actived.svg'),
  Red_Actived_1: require('./ByClassType/Active/4W/1-Red-Actived.svg'),
  Yellow_Actived_1: require('./ByClassType/Active/4W/1-Yellow-Actived.svg'),
  Purple_Actived_1: require('./ByClassType/Active/4W/1-Purple-Actived.svg'),
  Orange_Actived_1: require('./ByClassType/Active/4W/1-Orange-Actived.svg'),

  Green_Actived_2: require('./ByClassType/Active/6W/2-Green-Actived.svg'),
  Grey_Actived_2: require('./ByClassType/Active/6W/2-Grey-Actived.svg'),
  Red_Actived_2: require('./ByClassType/Active/6W/2-Red-Actived.svg'),
  Yellow_Actived_2: require('./ByClassType/Active/6W/2-Yellow-Actived.svg'),
  Purple_Actived_2: require('./ByClassType/Active/6W/2-Purple-Actived.svg'),
  Orange_Actived_2: require('./ByClassType/Active/6W/2-Orange-Actived.svg'),

  Green_Actived_3: require('./ByClassType/Active/10W/3-Green-Actived.svg'),
  Grey_Actived_3: require('./ByClassType/Active/10W/3-Grey-Actived.svg'),
  Red_Actived_3: require('./ByClassType/Active/10W/3-Red-Actived.svg'),
  Yellow_Actived_3: require('./ByClassType/Active/10W/3-Yellow-Actived.svg'),
  Purple_Actived_3: require('./ByClassType/Active/10W/3-Purple-Actived.svg'),
  Orange_Actived_3: require('./ByClassType/Active/10W/3-Orange-Actived.svg'),

  Green_Actived_4: require('./ByClassType/Active/12W/4-Green-Actived.svg'),
  Grey_Actived_4: require('./ByClassType/Active/12W/4-Grey-Actived.svg'),
  Red_Actived_4: require('./ByClassType/Active/12W/4-Red-Actived.svg'),
  Yellow_Actived_4: require('./ByClassType/Active/12W/4-Yellow-Actived.svg'),
  Purple_Actived_4: require('./ByClassType/Active/12W/4-Purple-Actived.svg'),
  Orange_Actived_4: require('./ByClassType/Active/12W/4-Orange-Actived.svg'),

  Green_Actived_5: require('./ByClassType/Active/BUS/5-Green-Actived.svg'),
  Grey_Actived_5: require('./ByClassType/Active/BUS/5-Grey-Actived.svg'),
  Red_Actived_5: require('./ByClassType/Active/BUS/5-Red-Actived.svg'),
  Yellow_Actived_5: require('./ByClassType/Active/BUS/5-Yellow-Actived.svg'),
  Purple_Actived_5: require('./ByClassType/Active/BUS/5-Purple-Actived.svg'),
  Orange_Actived_5: require('./ByClassType/Active/BUS/5-Orange-Actived.svg'),

  Green_Actived_6: require('./ByClassType/Active/TT/6-Green-Actived.svg'),
  Grey_Actived_6: require('./ByClassType/Active/TT/6-Grey-Actived.svg'),
  Red_Actived_6: require('./ByClassType/Active/TT/6-Red-Actived.svg'),
  Yellow_Actived_6: require('./ByClassType/Active/TT/6-Yellow-Actived.svg'),
  Purple_Actived_6: require('./ByClassType/Active/TT/6-Purple-Actived.svg'),
  Orange_Actived_6: require('./ByClassType/Active/TT/6-Orange-Actived.svg'),

  Green_Actived_0: require('./ByClassType/Active/Unknow/0-Green-Actived.svg'),
  Grey_Actived_0: require('./ByClassType/Active/Unknow/0-Grey-Actived.svg'),
  Red_Actived_0: require('./ByClassType/Active/Unknow/0-Red-Actived.svg'),
  Yellow_Actived_0: require('./ByClassType/Active/Unknow/0-Yellow-Actived.svg'),
  Purple_Actived_0: require('./ByClassType/Active/Unknow/0-Purple-Actived.svg'),
  Orange_Actived_0: require('./ByClassType/Active/Unknow/0-Orange-Actived.svg'),

  // GENERAL
  Green_1: require('./ByClassType/Inactived/4W/1-Green.svg'),
  Grey_1: require('./ByClassType/Inactived/4W/1-Grey.svg'),
  Red_1: require('./ByClassType/Inactived/4W/1-Red.svg'),
  Yellow_1: require('./ByClassType/Inactived/4W/1-Yellow.svg'),
  Purple_1: require('./ByClassType/Inactived/4W/1-Purple.svg'),
  Orange_1: require('./ByClassType/Inactived/4W/1-Orange.svg'),

  Green_2: require('./ByClassType/Inactived/6W/2-Green.svg'),
  Grey_2: require('./ByClassType/Inactived/6W/2-Grey.svg'),
  Red_2: require('./ByClassType/Inactived/6W/2-Red.svg'),
  Yellow_2: require('./ByClassType/Inactived/6W/2-Yellow.svg'),
  Purple_2: require('./ByClassType/Inactived/6W/2-Purple.svg'),
  Orange_2: require('./ByClassType/Inactived/6W/2-Orange.svg'),

  Green_3: require('./ByClassType/Inactived/10W/3-Green.svg'),
  Grey_3: require('./ByClassType/Inactived/10W/3-Grey.svg'),
  Red_3: require('./ByClassType/Inactived/10W/3-Red.svg'),
  Yellow_3: require('./ByClassType/Inactived/10W/3-Yellow.svg'),
  Purple_3: require('./ByClassType/Inactived/10W/3-Purple.svg'),
  Orange_3: require('./ByClassType/Inactived/10W/3-Orange.svg'),

  Green_4: require('./ByClassType/Inactived/12W/4-Green.svg'),
  Grey_4: require('./ByClassType/Inactived/12W/4-Grey.svg'),
  Red_4: require('./ByClassType/Inactived/12W/4-Red.svg'),
  Yellow_4: require('./ByClassType/Inactived/12W/4-Yellow.svg'),
  Purple_4: require('./ByClassType/Inactived/12W/4-Purple.svg'),
  Orange_4: require('./ByClassType/Inactived/12W/4-Orange.svg'),

  Green_5: require('./ByClassType/Inactived/BUS/5-Green.svg'),
  Grey_5: require('./ByClassType/Inactived/BUS/5-Grey.svg'),
  Red_5: require('./ByClassType/Inactived/BUS/5-Red.svg'),
  Yellow_5: require('./ByClassType/Inactived/BUS/5-Yellow.svg'),
  Purple_5: require('./ByClassType/Inactived/BUS/5-Purple.svg'),
  Orange_5: require('./ByClassType/Inactived/BUS/5-Orange.svg'),

  Green_6: require('./ByClassType/Inactived/TT/6-Green.svg'),
  Grey_6: require('./ByClassType/Inactived/TT/6-Grey.svg'),
  Red_6: require('./ByClassType/Inactived/TT/6-Red.svg'),
  Yellow_6: require('./ByClassType/Inactived/TT/6-Yellow.svg'),
  Purple_6: require('./ByClassType/Inactived/TT/6-Purple.svg'),
  Orange_6: require('./ByClassType/Inactived/TT/6-Orange.svg'),

  Green_0: require('./ByClassType/Inactived/Unknow/0-Green.svg'),
  Grey_0: require('./ByClassType/Inactived/Unknow/0-Grey.svg'),
  Red_0: require('./ByClassType/Inactived/Unknow/0-Red.svg'),
  Yellow_0: require('./ByClassType/Inactived/Unknow/0-Yellow.svg'),
  Purple_0: require('./ByClassType/Inactived/Unknow/0-Purple.svg'),
  Orange_0: require('./ByClassType/Inactived/Unknow/0-Orange.svg')

  //#endregion

}

export default images
